routes/web.php
    Route::resource('master/blog_category', 'Masters\BlogCategoryController');
    // Home Page Images
    Route::match(['get', 'post'], 'master/homepageimage/search', 'Masters\HomePageImageController@search')->name('homepageimage.search');
    Route::match(['put', 'patch'], 'master/homepageimage/restore/{source}', 'Masters\HomePageImageController@restore')->name('homepageimage.restore');
    Route::delete('master/homepageimage/delete/{source}', 'Masters\HomePageImageController@delete')->name('homepageimage.delete');
    Route::resource('master/homepageimage', 'Masters\HomePageImageController');
    // Banner Images
    Route::match(['get', 'post'], 'master/bannerimages/search', 'Masters\BannerImagesController@search')->name('bannerimages.search');
    Route::match(['put', 'patch'], 'master/bannerimages/restore/{source}', 'Masters\BannerImagesController@restore')->name('bannerimages.restore');
    Route::match(['post'], 'master/bannerimages/product_subcategory', 'Masters\BannerImagesController@product_subcategory')->name('bannerimages.product_subcategory');
    Route::delete('master/bannerimages/delete/{source}', 'Masters\BannerImagesController@delete')->name('bannerimages.delete');
    Route::resource('master/bannerimages', 'Masters\BannerImagesController');
    // Single Banner Image
    Route::match(['get', 'post'], 'master/singlebannerimage/search', 'Masters\SingleBannerImageController@search')->name('singlebannerimage.search');
    Route::match(['put', 'patch'], 'master/singlebannerimage/restore/{source}', 'Masters\SingleBannerImageController@restore')->name('singlebannerimage.restore');
    Route::match(['post'], 'master/singlebannerimage/product_subcategory', 'Masters\SingleBannerImageController@product_subcategory')->name('singlebannerimage.product_subcategory');
    Route::delete('master/singlebannerimage/delete/{source}', 'Masters\SingleBannerImageController@delete')->name('singlebannerimage.delete');
    Route::resource('master/singlebannerimage', 'Masters\SingleBannerImageController');
    // Banner Slider
    Route::match(['get', 'post'], 'master/bannerslider/search', 'Masters\BannersliderController@search')->name('bannerslider.search');
    Route::match(['put', 'patch'], 'master/bannerslider/restore/{source}', 'Masters\BannersliderController@restore')->name('bannerslider.restore');
    Route::delete('master/bannerslider/delete/{source}', 'Masters\BannersliderController@delete')->name('bannerslider.delete');
    Route::resource('master/bannerslider', 'Masters\BannersliderController');
    // Testimonial
    Route::match(['get', 'post'], 'testimonial/search', 'Testimonial\TestimonialController@search')->name('testimonial.search');
    Route::match(['put', 'patch'], 'testimonial/restore/{source}', 'Testimonial\TestimonialController@restore')->name('testimonial.restore');
    Route::delete('testimonial/delete/{source}', 'Testimonial\TestimonialController@delete')->name('testimonial.delete');
    Route::resource('testimonial', 'Testimonial\TestimonialController');
    // Team
    Route::match(['get', 'post'], 'team/search', 'Team\TeamController@search')->name('team.search');
    Route::match(['put', 'patch'], 'team/restore/{source}', 'Team\TeamController@restore')->name('team.restore');
    Route::delete('team/delete/{source}', 'Team\TeamController@delete')->name('team.delete');
    Route::resource('team', 'Team\TeamController');
    // Coupons
    Route::match(['get', 'post'], 'coupons/search', 'Coupons\CouponsController@search')->name('coupons.search');
    Route::match(['put', 'patch'], 'coupons/restore/{source}', 'Coupons\CouponsController@restore')->name('coupons.restore');
    Route::delete('coupons/delete/{source}', 'Coupons\CouponsController@delete')->name('coupons.delete');
    Route::resource('coupons', 'Coupons\CouponsController');
    // Default Master
    Route::resource('master', 'Masters\CategoryController');

    //Product ----------------------------------------------
    Route::delete('product/deletePic/{source}', 'Product\ProductController@deletePic')->name('product.deletePic');
    Route::match(['post'], 'product/savePics', 'Product\ProductController@savePics')->name('product.savePics');
    Route::match(['get', 'post'], 'product/pics/{source}', 'Product\ProductController@pics')->name('product.pics');
    Route::match(['get', 'post'], 'product/search', 'Product\ProductController@search')->name('product.search');
    Route::match(['post'], 'product/product_subcategory', 'Product\ProductController@product_subcategory')->name('product.product_subcategory');
    Route::match(['put', 'patch'], 'product/restore/{source}', 'Product\ProductController@restore')->name('product.restore');
    Route::match(['post'], 'product/shop_brands', 'Product\ProductController@shop_brands')->name('product.shop_brands');
    Route::match(['put', 'patch'], 'product/restore/{source}', 'Product\ProductController@restore')->name('product.restore');
    Route::delete('product/delete/{source}', 'Product\ProductController@delete')->name('product.delete');
    Route::resource('product', 'Product\ProductController');
    //Gallery Album
    Route::match(['get', 'post'], 'gallery/album/search', 'Gallery\AlbumController@search')->name('album.search');
    Route::match(['put', 'patch'], 'gallery/album/restore/{source}', 'Gallery\AlbumController@restore')->name('album.restore');
    Route::delete('gallery/album/delete/{source}', 'Gallery\AlbumController@delete')->name('album.delete');
    Route::resource('gallery/album', 'Gallery\AlbumController');
    // Gallery Photos
    Route::match(['get', 'post'], 'gallery/photo/search', 'Gallery\PhotoController@search')->name('photo.search');
    Route::match(['put', 'patch'], 'gallery/photo/restore/{source}', 'Gallery\PhotoController@restore')->name('photo.restore');
    Route::delete('gallery/photo/delete/{source}', 'Gallery\PhotoController@delete')->name('photo.delete');
    Route::resource('gallery/photo', 'Gallery\PhotoController');
    Route::resource('gallery', 'Gallery\AlbumController');

    //CMS
    Route::match(['get', 'post'], 'cms/search', 'CmsController@search')->name('cms.search');
    Route::match(['put', 'patch'], 'cms/restore/{source}', 'CmsController@restore')->name('cms.restore');
    Route::delete('cms/delete/{source}', 'CmsController@delete')->name('cms.delete');
    Route::resource('cms', 'CmsController');
    //Blogs   ----------------------------------------------
    Route::delete('blogs/deletePic/{source}', 'Blogs\BlogsController@deletePic')->name('blogs.deletePic');
    Route::match(['post'], 'blogs/savePics', 'Blogs\BlogsController@savePics')->name('blogs.savePics');
    Route::match(['get', 'post'], 'blogs/pics/{source}', 'Blogs\BlogsController@pics')->name('blogs.pics');
    Route::match(['get', 'post'], 'blogs/search', 'Blogs\BlogsController@search')->name('blogs.search');
    Route::match(['put', 'patch'], 'blogs/restore/{source}', 'Blogs\BlogsController@restore')->name('blogs.restore');
    Route::delete('blogs/delete/{source}', 'Blogs\BlogsController@delete')->name('blogs.delete');
    Route::resource('blogs', 'Blogs\BlogsController');
    //Support -> Management Email
    Route::match(['get', 'post'], 'management/search', 'Support\ManagementController@search')->name('management.search');
    Route::match(['put', 'patch'], 'management/restore/{source}', 'Support\ManagementController@restore')->name('management.restore');
    Route::delete('management/delete/{source}', 'Support\ManagementController@delete')->name('management.delete');
    Route::resource('management', 'Support\ManagementController');  

    // Settings
    Route::match(['put', 'patch'], 'setting/restore/{source}', 'SettingController@restore')->name('setting.restore');
    Route::delete('setting/delete/{source}', 'SettingController@delete')->name('setting.delete');
    Route::resource('setting', 'SettingController');
    //Messages
    Route::match(['get', 'post'], 'message/search', 'Message\MessageController@search')->name('message.search');
    Route::match(['put', 'patch'], 'message/restore/{source}', 'Message\MessageController@restore')->name('message.restore');
    Route::match(['get', 'post'], 'message/search', 'Message\MessageController@search')->name('message.search');
    Route::delete('message/delete/{source}', 'Message\MessageController@delete')->name('message.delete');
    Route::resource('message', 'Message\MessageController');

    //Order List
    Route::match(['get', 'post'], 'orders/search', 'Orders\OrdersController@search')->name('orders.search');
    Route::match(['get', 'post'], 'orders/orderDetailsSearch', 'Orders\OrdersController@orderDetailsSearch')->name('orders.orderDetailsSearch');
    Route::match(['get', 'post'], 'orders/show/{source}', 'Orders\OrdersController@show')->name('orders.show');
    Route::match(['get', 'post'], 'orders/updateOrderStatus', 'Orders\OrdersController@updateOrderStatus')->name('orders.updateOrderStatus');
    Route::resource('orders', 'Orders\OrdersController');

});


//Frontend
Route::resource('/', 'HomeController');
//Route::get('/home', 'HomeController@index')->name('frontend.index');
Route::get('/about-us', 'HomeController@aboutus');
Route::get('/contact-us', 'HomeController@contactus');
Route::get('/blog', 'HomeController@allblogs');
Route::get('/blog/{slug}', 'HomeController@blog_detail');
Route::get('/shop', 'HomeController@shopProducts');
Route::get('/shop/{slug}', 'HomeController@product_detail');

Route::get('/search', 'HomeController@productSearch');

Route::get('/login-register', 'HomeController@login_register');
Route::get('/account', 'HomeController@myAccount');
Route::get('/wishlist', 'HomeController@userWishlist');
Route::get('/cart', 'HomeController@userCart');
Route::get('/checkout', 'HomeController@userCheckout');
Route::post('/contactform', 'HomeController@contactform');
Route::post('/sendcomment', 'HomeController@sendcomment');
Route::post('/usersignup', 'HomeController@usersignup');

resources/views/coupons/create.blade.php
<div class="row">
	<div class="col-12">
		<form action="{{ route('coupons.store') }}" enctype="multipart/form-data" method="POST" id="brand_form">
			<div class="form-group">
				<label class="form-control-label" for="name"><strong>Coupon Name</strong><small class="text-danger"> (required)</small></label>
				<input type="text" class="form-control" name="name" value="{{ old('name') }}" autofocus>
				<small class="form-control-feedback"></small>
			</div>
			<div class="form-group">
				<label class="form-control-label" for="product_status"><strong>Coupon Type</strong></label>
				<select name="type" class="form-control">
					<option value=""{{ empty(old('type')) ? ' selected="selected"' : '' }}></option>
					@foreach ($bladeVar['couponType'] as $key => $type)
						<option value="{{ $type }}"{{ $type == old('type') ? ' selected="selected"' : '' }}>{{ $type }}</option>
					@endforeach
				</select>
				<small class="form-control-feedback"></small>
			</div>
			<div class="form-group">
				<label class="form-control-label" for="value"><strong>Coupon Value</strong></label>
				<input type="text" class="form-control" name="value" value="{{ old('value') }}" autofocus>
				<small class="form-control-feedback"></small>
			</div>
			<div class="form-group">
				<label class="form-control-label" for="quantity"><strong>Coupon Quantity</strong></label>
				<input type="text" class="form-control" name="quantity" value="{{ old('quantity') }}" autofocus>
				<small class="form-control-feedback"></small>
			</div>
			<div class="form-group">
				<label class="form-control-label" for="expiry"><strong>Coupon Expiry</strong></label>
				<input type="text" class="form-control" id="expiry" name="expiry" value="{{ old('expiry') }}" autofocus>
				<small class="form-control-feedback"></small>
			</div>
			<div class="form-group text-right">
     			<button class="btn btn-success upload-image" type="submit">Submit</button>
     			<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    		</div> 
		</form>
	</div>
</div>
<script type="text/javascript">
$('#expiry').datetimepicker();
</script>  

resources/views/coupons/edit.blade.php
<div class="row">
	<div class="col-12">
		<form action="{{ route('coupons.update', $bladeVar['result']->id) }}" enctype="multipart/form-data" method="POST" id="brand_form">
			{{ method_field('PUT') }}
			<div class="form-group">
				<label class="form-control-label" for="name"><strong>Coupon Name</strong><small class="text-danger"> (required)</small></label>
				<input type="text" class="form-control" name="name" value="{{ old('name', $bladeVar['result']->name) }}" autofocus>
				<small class="form-control-feedback"></small>
			</div>
			<div class="form-group">
				<label class="form-control-label" for="product_status"><strong>Coupon Type</strong></label>
				<select name="type" class="form-control">
					<option value=""{{ empty(old('type')) ? ' selected="selected"' : '' }}></option>
					@foreach ($bladeVar['couponType'] as $key => $type)
						<option value="{{ $type }}"{{ $type == old('type', $bladeVar['result']->type) ? ' selected="selected"' : '' }}>{{ $type }}</option>
					@endforeach
				</select>
				<small class="form-control-feedback"></small>
			</div>
			<div class="form-group">
				<label class="form-control-label" for="value"><strong>Coupon Value</strong></label>
				<input type="text" class="form-control" name="value" value="{{ old('value', $bladeVar['result']->value) }}" autofocus>
				<small class="form-control-feedback"></small>
			</div>
			<div class="form-group">
				<label class="form-control-label" for="quantity"><strong>Coupon Quantity</strong></label>
				<input type="text" class="form-control" name="quantity" value="{{ old('quantity', $bladeVar['result']->quantity) }}" autofocus>
				<small class="form-control-feedback"></small>
			</div>
			<div class="form-group">
				<label class="form-control-label" for="expiry"><strong>Coupon Expiry</strong></label>
				<input type="text" class="form-control" name="expiry" value="{{ old('expiry', $bladeVar['result']->expiry) }}" autofocus>
				<small class="form-control-feedback"></small>
			</div>
			 <div class="form-group text-right">
     			<button class="btn btn-success upload-image" type="submit">Submit</button>
     			<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    		</div> 
		</form>
	</div>
</div>
<script type="text/javascript">
$('#expiry').datetimepicker();
</script> 

resources/views/coupons/show.blade.php
<div class="row">
	<div class="col-12">
		<table class="table table-bordered table-sm mb-0">
		    <tbody>
		    	<tr>
		    		<th class="bg-faded" style="width: 8rem;">Id</th>
		    		<td>{{ $bladeVar['result']->id }}</td>
		    	</tr>
				<tr>
		    		<th class="bg-faded">Coupon Name</th>
		    		<td>{{ $bladeVar['result']->name }}</td>
		    	</tr>
				<tr>
		    		<th class="bg-faded">Coupon Type</th>
		    		<td>{{ $bladeVar['result']->type }}</td>
				</tr>
				<tr>
		    		<th class="bg-faded">Coupon Value</th>
		    		<td>{{ $bladeVar['result']->value }}</td>
		    	</tr>
				<tr>
		    		<th class="bg-faded">Coupon Quantity</th>
		    		<td>{{ $bladeVar['result']->quantity }}</td>
		    	</tr>
				<tr>
		    		<th class="bg-faded">Coupon Expiry</th>
		    		<td>{{ $bladeVar['result']->expiry }}</td>
		    	</tr>
		    </tbody>
    	</table>
    	<span class="modalUrls hidden-xs-up" 
	    	data-edit="{{ $bladeVar['result']->deleted_at == null ? route('coupons.edit', $bladeVar['result']->id) : '' }}" 
	    	data-destroy="{{ $bladeVar['result']->deleted_at == null ? route('coupons.destroy', $bladeVar['result']->id) : '' }}" 
	    	data-restore="{{ $bladeVar['result']->deleted_at != null ? route('coupons.restore', $bladeVar['result']->id) : '' }}"
	    	data-delete="{{ route('coupons.delete', $bladeVar['result']->id) }}">
	    </span>
	</div>
</div>	    