routes/web.php
    Route::match(['put', 'patch'], 'master/singlebannerimage/restore/{source}', 'Masters\SingleBannerImageController@restore')->name('singlebannerimage.restore');
    Route::match(['post'], 'master/singlebannerimage/product_subcategory', 'Masters\SingleBannerImageController@product_subcategory')->name('singlebannerimage.product_subcategory');
    Route::delete('master/singlebannerimage/delete/{source}', 'Masters\SingleBannerImageController@delete')->name('singlebannerimage.delete');
    Route::resource('master/singlebannerimage', 'Masters\SingleBannerImageController');
    // Banner Slider
    Route::match(['get', 'post'], 'master/bannerslider/search', 'Masters\BannersliderController@search')->name('bannerslider.search');
    Route::match(['put', 'patch'], 'master/bannerslider/restore/{source}', 'Masters\BannersliderController@restore')->name('bannerslider.restore');
    Route::delete('master/bannerslider/delete/{source}', 'Masters\BannersliderController@delete')->name('bannerslider.delete');
    Route::resource('master/bannerslider', 'Masters\BannersliderController');
    // Testimonial
    Route::match(['get', 'post'], 'testimonial/search', 'Testimonial\TestimonialController@search')->name('testimonial.search');
    Route::match(['put', 'patch'], 'testimonial/restore/{source}', 'Testimonial\TestimonialController@restore')->name('testimonial.restore');
    Route::delete('testimonial/delete/{source}', 'Testimonial\TestimonialController@delete')->name('testimonial.delete');
    Route::resource('testimonial', 'Testimonial\TestimonialController');
    // Team
    Route::match(['get', 'post'], 'team/search', 'Team\TeamController@search')->name('team.search');
    Route::match(['put', 'patch'], 'team/restore/{source}', 'Team\TeamController@restore')->name('team.restore');
    Route::delete('team/delete/{source}', 'Team\TeamController@delete')->name('team.delete');
    Route::resource('team', 'Team\TeamController');
    // Coupons
    Route::match(['get', 'post'], 'coupons/search', 'Coupons\CouponsController@search')->name('coupons.search');
    Route::match(['put', 'patch'], 'coupons/restore/{source}', 'Coupons\CouponsController@restore')->name('coupons.restore');
    Route::delete('coupons/delete/{source}', 'Coupons\CouponsController@delete')->name('coupons.delete');
    Route::resource('coupons', 'Coupons\CouponsController');
    // Default Master
    Route::resource('master', 'Masters\CategoryController');

    //Product ----------------------------------------------
    Route::delete('product/deletePic/{source}', 'Product\ProductController@deletePic')->name('product.deletePic');
    Route::match(['post'], 'product/savePics', 'Product\ProductController@savePics')->name('product.savePics');
    Route::match(['get', 'post'], 'product/pics/{source}', 'Product\ProductController@pics')->name('product.pics');
    Route::match(['get', 'post'], 'product/search', 'Product\ProductController@search')->name('product.search');
    Route::match(['post'], 'product/product_subcategory', 'Product\ProductController@product_subcategory')->name('product.product_subcategory');
    Route::match(['put', 'patch'], 'product/restore/{source}', 'Product\ProductController@restore')->name('product.restore');
    Route::match(['post'], 'product/shop_brands', 'Product\ProductController@shop_brands')->name('product.shop_brands');
    Route::match(['put', 'patch'], 'product/restore/{source}', 'Product\ProductController@restore')->name('product.restore');
    Route::delete('product/delete/{source}', 'Product\ProductController@delete')->name('product.delete');
    Route::resource('product', 'Product\ProductController');
    //Gallery Album
    Route::match(['get', 'post'], 'gallery/album/search', 'Gallery\AlbumController@search')->name('album.search');
    Route::match(['put', 'patch'], 'gallery/album/restore/{source}', 'Gallery\AlbumController@restore')->name('album.restore');
    Route::delete('gallery/album/delete/{source}', 'Gallery\AlbumController@delete')->name('album.delete');
    Route::resource('gallery/album', 'Gallery\AlbumController');
    // Gallery Photos
    Route::match(['get', 'post'], 'gallery/photo/search', 'Gallery\PhotoController@search')->name('photo.search');
    Route::match(['put', 'patch'], 'gallery/photo/restore/{source}', 'Gallery\PhotoController@restore')->name('photo.restore');
    Route::delete('gallery/photo/delete/{source}', 'Gallery\PhotoController@delete')->name('photo.delete');
    Route::resource('gallery/photo', 'Gallery\PhotoController');
    Route::resource('gallery', 'Gallery\AlbumController');

    //CMS
    Route::match(['get', 'post'], 'cms/search', 'CmsController@search')->name('cms.search');
    Route::match(['put', 'patch'], 'cms/restore/{source}', 'CmsController@restore')->name('cms.restore');
    Route::delete('cms/delete/{source}', 'CmsController@delete')->name('cms.delete');
    Route::resource('cms', 'CmsController');
    //Blogs   ----------------------------------------------
    Route::delete('blogs/deletePic/{source}', 'Blogs\BlogsController@deletePic')->name('blogs.deletePic');
    Route::match(['post'], 'blogs/savePics', 'Blogs\BlogsController@savePics')->name('blogs.savePics');
    Route::match(['get', 'post'], 'blogs/pics/{source}', 'Blogs\BlogsController@pics')->name('blogs.pics');
    Route::match(['get', 'post'], 'blogs/search', 'Blogs\BlogsController@search')->name('blogs.search');
    Route::match(['put', 'patch'], 'blogs/restore/{source}', 'Blogs\BlogsController@restore')->name('blogs.restore');
    Route::delete('blogs/delete/{source}', 'Blogs\BlogsController@delete')->name('blogs.delete');
    Route::resource('blogs', 'Blogs\BlogsController');
    //Support -> Management Email
    Route::match(['get', 'post'], 'management/search', 'Support\ManagementController@search')->name('management.search');
    Route::match(['put', 'patch'], 'management/restore/{source}', 'Support\ManagementController@restore')->name('management.restore');
    Route::delete('management/delete/{source}', 'Support\ManagementController@delete')->name('management.delete');
    Route::resource('management', 'Support\ManagementController');  

    // Settings
    Route::match(['put', 'patch'], 'setting/restore/{source}', 'SettingController@restore')->name('setting.restore');
    Route::delete('setting/delete/{source}', 'SettingController@delete')->name('setting.delete');
    Route::resource('setting', 'SettingController');
    //Messages
    Route::match(['get', 'post'], 'message/search', 'Message\MessageController@search')->name('message.search');
    Route::match(['put', 'patch'], 'message/restore/{source}', 'Message\MessageController@restore')->name('message.restore');
    Route::match(['get', 'post'], 'message/search', 'Message\MessageController@search')->name('message.search');
    Route::delete('message/delete/{source}', 'Message\MessageController@delete')->name('message.delete');
    Route::resource('message', 'Message\MessageController');

    //Order List
    Route::match(['get', 'post'], 'orders/search', 'Orders\OrdersController@search')->name('orders.search');
    Route::match(['get', 'post'], 'orders/orderDetailsSearch', 'Orders\OrdersController@orderDetailsSearch')->name('orders.orderDetailsSearch');
    Route::match(['get', 'post'], 'orders/show/{source}', 'Orders\OrdersController@show')->name('orders.show');
    Route::match(['get', 'post'], 'orders/updateOrderStatus', 'Orders\OrdersController@updateOrderStatus')->name('orders.updateOrderStatus');
    Route::resource('orders', 'Orders\OrdersController');

});


//Frontend
Route::resource('/', 'HomeController');
//Route::get('/home', 'HomeController@index')->name('frontend.index');
Route::get('/about-us', 'HomeController@aboutus');
Route::get('/contact-us', 'HomeController@contactus');
Route::get('/blog', 'HomeController@allblogs');
Route::get('/blog/{slug}', 'HomeController@blog_detail');
Route::get('/shop', 'HomeController@shopProducts');
Route::get('/shop/{slug}', 'HomeController@product_detail');

Route::get('/search', 'HomeController@productSearch');

Route::get('/login-register', 'HomeController@login_register');
Route::get('/account', 'HomeController@myAccount');
Route::get('/wishlist', 'HomeController@userWishlist');
Route::get('/cart', 'HomeController@userCart');
Route::get('/checkout', 'HomeController@userCheckout');
Route::post('/contactform', 'HomeController@contactform');
Route::post('/sendcomment', 'HomeController@sendcomment');
Route::post('/usersignup', 'HomeController@usersignup');
Route::post('/userlogin', 'HomeController@userlogin');
Route::post('/userlogout', 'HomeController@userlogout');
Route::post('/userforgotPassword', 'HomeController@userforgotPassword');
Route::get('/recover-password', 'HomeController@userResetPassword');
Route::post('/userRecoverPassword', 'HomeController@userRecoverPassword');
Route::post('/userDetails', 'HomeController@userDetails');
Route::post('/updatePassword', 'HomeController@updatePassword');

// E-Shopping API
Route::post('/addtowishlist', 'HomeController@addToWishlist');
Route::post('/addtocart', 'HomeController@addToCart');
Route::post('/viewcart', 'HomeController@getViewcartItems');
Route::post('/updatecart', 'HomeController@updateCart');
Route::post('/removecartitem', 'HomeController@removeCartItem');
Route::post('/applycoupon', 'HomeController@applyCoupon');
Route::post('/removecoupon', 'HomeController@removeCoupon');
Route::post('/placeorder', 'HomeController@placeOrder');
Route::post('/addressBook', 'HomeController@addressBook');
Route::post('/myOrders', 'HomeController@myOrders');
Route::get('/ordersuccess', 'HomeController@userOrdersuccess');
Route::get('/ordercancel', 'HomeController@userOrdercancel');
Route::get('/orderDetail/{slug}', 'HomeController@orderDetail');
Route::post('/orderCancel', 'HomeController@orderCancel');

// payment form
Route::get('/paypalPayment', 'HomeController@paypalPayment');  
Route::post('/paypal', 'HomeController@payWithpaypal'); 

app/Http/Controllers/Support/ManagementController.php
<?php

namespace App\Http\Controllers\Support;
use Auth;
use App\Support\Management;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ManagementController extends Controller
{
   protected $sortable = [
        'id' => '_id',
        'email' => 'email'
    ];

    protected $pageTitle = 'Management Email';
    protected $activeNav = [
        'nav' => 'management',
        'sub' => 'management'

    ];
    protected $breadcrumb_master = 'Management Email';
    protected $view_master = 'support.management.';
    protected $route_master = 'management.';

   public function __construct()
    {

     $this->bladeVar['page']['title'] = $this->pageTitle;
     $this->bladeVar['page']['activeNav'] = $this->activeNav;
     $this->bladeVar['page']['breadcrumb'] = ['Home' => '/'];
     $this->bladeVar['page']['breadcrumb'][$this->breadcrumb_master] = route($this->route_master.'index');
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request){   
	    $this->bladeVar['page']['breadcrumb'][$this->breadcrumb_master] = '';
        $this->bladeVar['results'] = Management::withTrashed()
           ->orderBy($this->sortable[$request->input('sort', 'id')], $request->input('dir', 'DESC'))
            ->paginate($this->paginate_total);
        $this->bladeVar['total_count'] = Management::withTrashed()->count();
        return view($this->view_master.'index', ['bladeVar' => $this->bladeVar]);
    }
	
	    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function search(Request $request)
    {
        if (!$request->q) {
            return redirect(route($this->route_master.'index'));
        }
        $this->bladeVar['page']['breadcrumb'][$this->breadcrumb_master] = route($this->route_master.'index');
        $this->bladeVar['page']['breadcrumb']['Search'] = '';
        $this->bladeVar['results'] = Management::withTrashed()
            ->where('email', 'like', '%'.$request->q.'%')
            ->orderBy($this->sortable[$request->input('sort', 'id')], $request->input('dir', 'ASC'))
            ->paginate($this->paginate_total);
        $this->bladeVar['total_count'] = Management::withTrashed()
            ->where('email', 'like', '%'.$request->q.'%')
            ->count();
        return view($this->view_master.'index', ['bladeVar' => $this->bladeVar]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        if ($request->ajax()) {
            return view($this->view_master.'create', ['bladeVar' => $this->bladeVar]);
        } else {
            return redirect(route($this->route_master.'index'));
        }
    }
	
	    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request){
        $management = Management::create([
             'email' => $request->email,
             'created_by'=> Auth::id(),
        ]);
        return response()->json(['success' => '<strong>Success!</strong> data saved for management email <strong>'.$request->email.'</strong><a href="'.route($this->route_master.'show', $management->_id).'" class="btn btn-sm btn-info" title="View this management email" data-toggle="modal" data-target="#viewModal"> Click here to view it</a>']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, $id)
    {
        if ($request->ajax()) {
            $this->bladeVar['result'] = Management::withTrashed()->find($id);

            return view($this->view_master.'show', ['bladeVar' => $this->bladeVar]);
        } else {
            return redirect(route($this->route_master.'index'));
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, $id)
    {
        if ($request->ajax()) {
            $this->bladeVar['result'] = Management::find($id);
            return view($this->view_master.'edit', ['bladeVar' => $this->bladeVar]);
        } else {
            return redirect(route($this->route_master.'index'));
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $input = $request->all();
		$management = Management::find($id);
		$management->update([
		'email' => $request->email,
		'updated_by'=>Auth::id(),
		]);
		return response()->json([
		'success' => '<strong>Success!</strong> Data updated for management email <strong>'.$request->email.'</strong> <a href="'.route($this->route_master.'show', $management->_id).'" class="btn btn-sm btn-info" title="View this management email" data-toggle="modal" data-target="#viewModal">Click here to view it</a>'
		]);
    
     
    }

     /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id){ 
	   $management = Management::find($id);
       $management->delete();

        return response()->json([
            'success' => '<strong>Success!</strong> management email has been deleted temporarily!'
        ]);
    }

    /**
     * Mark as deleted the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function delete($id){
        $management = Management::withTrashed()->find($id);
        $management->forceDelete();
        return response()->json([
            'success' => '<strong>Success!</strong> management email has been deleted permanently!'
        ]);
    }

    /**
     * Restores deleted marked resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function restore($id){
        Management::withTrashed()->find($id)->restore();
        return response()->json([
            'success' => '<strong>Success!</strong> management has been restored!'
        ]);
    }	

}

resources/views/support/management/create.blade.php
<div class="row">
	<div class="col-12">
		<form action="{{ route('management.store') }}" enctype="multipart/form-data" method="POST" id="brand_form">
		  <div class="row">
			<div class="col-6">
			<div class="form-group">
				<label class="form-control-label" for="email"><strong>Email</strong><!--<small class="text-danger">(required)</small>--></label>
				<input type="text" class="form-control" name="email" value="{{ old('email') }}" autofocus>
				<small class="form-control-feedback"></small>
			</div>
			</div>
			</div>
			 <div class="form-group text-right">
     			  <button class="btn btn-success upload-image" type="submit">Submit</button>
     			  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    		</div>
		</form>
	</div>
</div>

resources/views/support/management/edit.blade.php
<div class="row">
	<div class="col-12">
		<form action="{{ route('management.update', $bladeVar['result']->_id) }}" method="POST">
			{{ method_field('PUT') }}
			 <div class="row">
			<div class="col-6">
			<div class="form-group">
				<label class="form-control-label" for="email"><strong>Email</strong> <!--<small class="text-danger">(required)</small>--></label>
				<input type="text" class="form-control" name="email" value="{{ old('email', $bladeVar['result']->email) }}" autofocus>
				<small class="form-control-feedback"></small>
			</div>
			</div>
			</div>
			 <div class="form-group text-right">
     			<button class="btn btn-success upload-image" type="submit">Submit</button>
     			  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    		</div>
      	</form>
    </div>
</div>

resources/views/support/management/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container-fluid" id="pageContainer">
        <div class="row" id="pageContent">
            <div class="col-12 col-md-8 offset-md-2">
                <div class="float-right mt-2 hidden-xs-down">
                <a href="{{ route('management.create') }}" class="btn btn-success" role="button" title="Create New Email" data-toggle="modal" data-target="#createModal"><i class="fa fa-plus"></i><span class="hidden-sm-down"> Create New</span></a>
                    <a href="{{ route('management.index') }}" class="btn btn-secondary btn-search" title="Search category" data-search="{{ !empty(Request::input('q')) ? 'yes' : ''}}"><i class="fa fa-search"></i><span{!! !empty(Request::input('q')) ? '' : ' class="hidden-xs-up"' !!}> Close</span></a>
                    <a href="{{ route('management.index') }}" class="btn btn-secondary" role="button" title="Refresh Management Email List"><i class="fa fa-refresh"></i></a>
                </div>
                <div class="float-right mt-1 hidden-sm-up">
                    <a href="{{ route('management.create') }}" class="btn btn-success btn-sm" role="button" title="Create New category" data-toggle="modal" data-target="#createModal"><i class="fa fa-plus"></i></a>
                    <a href="{{ route('management.index') }}" class="btn btn-secondary btn-sm btn-search" title="Search category" data-search="{{ !empty(Request::input('q')) ? 'yes' : ''}}"><i class="fa fa-search"></i><span{!! !empty(Request::input('q')) ? '' : ' class="hidden-xs-up"' !!}> Close</span></a>
                    <a href="{{ route('management.index') }}" class="btn btn-secondary btn-sm" role="button" title="Refresh Management Email List"><i class="fa fa-refresh"></i></a>
                </div>
                <h1 class="hidden-xs-down">{{ Request::input('q') ? 'Search ' : '' }}Email <span class="text-muted h5">(total {{ number_format($bladeVar['total_count']) }})</span></h1>
                <h1 class="hidden-sm-up h3">{{ Request::input('q') ? 'Search ' : '' }}Email <br><span class="text-muted h6">(total {{ number_format($bladeVar['total_count']) }})</span></h1>
                <div class="clearfix alertArea"></div>
                <div class="card mb-2 searchContainer{{ Request::input('q') ? '' : ' hidden-xs-up'}}">
                    <div class="card-block">
                        <form method="get" action="{{ route('management.search') }}" class="m0 p0 form-search">
                            <div class="form-group mb-0">
                                <label class="form-control-label" for="q"><strong>Search by email</strong></label>
                                <input type="text" class="form-control" name="q" value="{{ Request::input('q') }}">
                                <small class="form-text text-muted">Type Email and hit "Enter" key to search</small>
                            </div>
                        </form>
                    </div>
                </div>

                @if ($bladeVar['total_count'] > 0)
                    <table class="table table-bordered table-hover table-sm">
                        <thead class="bg-faded">
                            <tr>
                                <th class="text-center" style="width: 4rem;"><nobr><a href="{{ url()->current() }}?{{ Request::input('q') ? 'q='.Request::input('q').'&' : '' }}sort=id&dir={{ Request::input('sort') == 'id' ? Request::input('dir') == 'asc' ? 'desc' : 'asc' : 'asc' }}">Id</a> <i class="fa fa-{{ Request::input('sort') == 'id' ? Request::input('dir') == 'asc' ? 'sort-numeric-asc' : 'sort-numeric-desc' : 'sort' }}"></i></nobr></th>
                                <th><nobr>Email</nobr></th>
                                <th class="w-td-action">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($bladeVar['results'] as $rs)
                                <tr>
                                    <td class="text-center"><span>{{ $rs->_id }}</span></td>
                                    <td>{{ $rs->email }}</td>
                                    <td class="text-center text-sm-left">
                                        <div class="hidden-xs-down">
                                            <a href="{{ route('management.show', $rs->_id) }}" class="btn btn-sm btn-info" title="View" data-toggle="modal" data-target="#viewModal"><i class="fa fa-eye"></i></a>
                                            <a href="{{ route('management.delete', $rs->_id) }}" class="btn btn-sm btn-danger btn-delete" title="Delete permanently"><i class="fa fa-trash"></i></a>
                                        </div>
                                        <div class="btn-group hidden-sm-up">
                                            <button type="button" class="btn btn-sm btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Actions</button>
                                            <div class="dropdown-menu dropdown-menu-right">
                                                <a href="{{ route('management.show', $rs->_id) }}" class="dropdown-item" data-toggle="modal" data-target="#viewModal"><i class="fa fa-eye text-info"></i> View</a>
                                                
                                                <a href="{{ route('management.delete', $rs->_id) }}" class="dropdown-item btn-delete"><i class="fa fa-trash text-danger"></i> Delete permanently</a>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                    @if ($bladeVar['total_count'] > 20)
                    <div class="mt-4">
                        {{ $bladeVar['results']->appends(Request::query())->links() }}
                        <small class="d-block text-center text-muted">(showing 20 results per page)</small>
                    </div>
                    @endif
                @else
                    <div class="alert alert-success">
                        <strong>No records found!</strong>
                        @if (!empty(Request::input('q')))
                            No matching your search criteria. 
                        @else 
                            No Email added yet, please click on "Create New" button to add a management email. 
                        @endif
                    </div>
                @endif
                <!-- Deletetion code with Form -->
                <form class="formDelete">
                    {{ method_field('DELETE') }}
                </form>

                <!-- View modal code: START -->
                <div class="modal" id="viewModal" tabindex="-1" role="dialog" aria-labelledby="viewModalTitle" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="viewModalTitle">View Management Email </h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <div class="my-5 text-center"><i class="fa fa-spinner fa-spin fa-3x fa-fw"></i></div>
                            </div>
                            <div class="modal-footer hidden-xs-up">
                                <a href="javascript:void(0);" class="btn btn-info btn-edit" title="Edit" data-toggle="modal" data-target="#editModal"><i class="fa fa-pencil"></i> Edit</a>
                                <a href="javascript:void(0);" class="btn btn-danger btn-delete" title="Delete permanently"><i class="fa fa-trash"></i></a>
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- View modal code: END -->

                <!-- Edit modal code: START -->
                <div class="modal" id="editModal" tabindex="-1" role="dialog" aria-labelledby="editModalTitle" aria-hidden="true">
                    <div class="modal-dialog modal-lg" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="editModalTitle">Edit Management Email </h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <div class="my-5 text-center"><i class="fa fa-spinner fa-spin fa-3x fa-fw"></i></div>
                            </div>
                            <div class="modal-footer hidden-xs-up">
                               <!--  <button type="button" class="btn btn-success btn-submit">Submit</button> -->
                               <!--  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button> -->
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Edit modal code: END -->

                <!-- Add modal code: START -->
                <div class="modal" id="createModal" tabindex="-1" role="dialog" aria-labelledby="createModalTitle" aria-hidden="true">
                    <div class="modal-dialog modal-lg" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="createModalTitle">Add Management Email </h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <div class="my-5 text-center"><i class="fa fa-spinner fa-spin fa-3x fa-fw"></i></div>
                            </div>
                            <div class="modal-footer hidden-xs-up">
                              <!--   <button type="button" class="btn btn-success btn-submit">Submit</button> -->
                              <!--   <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button> -->
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Add modal code: END -->
            </div>
        </div>
    </div>
@endsection

@section('foot')
    <script type="text/javascript">
        var pageUrl = '{{ route("management.index") }}';
        var ajaxLoadUrl = '{{ url()->full() }}';
        var pageContainer = '#pageContainer';
        var pageContent = '#pageContent';
    </script>
    <script src="{{ asset('js/jquery.form.js') }}"></script>
    <script src="{{ asset('js/management.js?v=1') }}"></script>
@endsection

resources/views/support/management/show.blade.php
<div class="row">
	<div class="col-12">
		<table class="table table-bordered table-sm mb-0">
		    <tbody>
		    	<tr>
		    		<th class="bg-faded" style="width: 8rem;">Id</th>
		    		<td>{{ $bladeVar['result']->_id }}</td>
		    	</tr>
		    	<tr>
		    		<th class="bg-faded">Email</th>
		    		<td>{{ $bladeVar['result']->email }}</td>
		    	</tr>
		    </tbody>
    	</table>
    	<span class="modalUrls hidden-xs-up" 
	    	data-edit="{{ route('management.edit', $bladeVar['result']->_id) }}"
	    	data-delete="{{ route('management.delete', $bladeVar['result']->_id) }}">
	    </span>
	</div>
</div>	    