routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::middleware(['auth', 'web'])->group(function () {
    Route::get('/admin', 'BootController@index')->name('boot');
});

Route::get('admin/login', function () {
    return view('auth/login');
});

Route::group(['middleware' => 'App\Http\Middleware\AdminMiddleware'], function(){ 
    //Settings - Flush Cache
    Route::get('/setting/cache/flush', function () {
        Cache::flush();
        return redirect(route('boot'))->with('flushcache', '<strong>Cache Flushed!</strong> Entire cache of the system has been flushed!');
    })->name('cache.flush');

    // Site Users
    Route::match(['get', 'post'], 'siteusers/search', 'SiteUsersController@search')->name('siteusers.search');
    Route::match(['put', 'patch'], 'siteusers/restore/{source}', 'SiteUsersController@restore')->name('siteusers.restore');
    Route::delete('siteusers/delete/{source}', 'SiteUsersController@delete')->name('siteusers.delete');
    Route::resource('siteusers', 'SiteUsersController');
    // Category
    Route::match(['get', 'post'], 'master/category/search', 'Masters\CategoryController@search')->name('category.search');
    Route::match(['put', 'patch'], 'master/category/restore/{source}', 'Masters\CategoryController@restore')->name('category.restore');
    Route::delete('master/category/delete/{source}', 'Masters\CategoryController@delete')->name('category.delete');
    Route::resource('master/category', 'Masters\CategoryController');
    // Brand
    Route::match(['get', 'post'], 'master/brand/search', 'Masters\BrandController@search')->name('brand.search');
    Route::match(['put', 'patch'], 'master/brand/restore/{source}', 'Masters\BrandController@restore')->name('brand.restore');
    Route::delete('master/brand/delete/{source}', 'Masters\BrandController@delete')->name('brand.delete');
    Route::resource('master/brand', 'Masters\BrandController');
    // Store
    Route::match(['get', 'post'], 'master/store/search', 'Masters\StoreController@search')->name('store.search');
    Route::match(['put', 'patch'], 'master/store/restore/{source}', 'Masters\StoreController@restore')->name('store.restore');
    Route::delete('master/store/delete/{source}', 'Masters\StoreController@delete')->name('store.delete');
    Route::resource('master/store', 'Masters\StoreController');
    // Store Category
    Route::match(['get', 'post'], 'master/store_category/search', 'Masters\StoreCategoryController@search')->name('store_category.search');
    Route::match(['put', 'patch'], 'master/store_category/restore/{source}', 'Masters\StoreCategoryController@restore')->name('store_category.restore');
    Route::delete('master/store_category/delete/{source}', 'Masters\StoreCategoryController@delete')->name('store_category.delete');
    Route::resource('master/store_category', 'Masters\StoreCategoryController');
    // Store Subategory
    Route::match(['get', 'post'], 'master/store_subcategory/search', 'Masters\StoreSubcategoryController@search')->name('store_subcategory.search');
    Route::match(['put', 'patch'], 'master/store_subcategory/restore/{source}', 'Masters\StoreSubcategoryController@restore')->name('store_subcategory.restore');
    Route::delete('master/store_subcategory/delete/{source}', 'Masters\StoreSubcategoryController@delete')->name('store_subcategory.delete');
    Route::resource('master/store_subcategory', 'Masters\StoreSubcategoryController');
    // Product Category
    Route::match(['get', 'post'], 'master/product_category/search', 'Masters\ProductCategoryController@search')->name('product_category.search');
    Route::match(['put', 'patch'], 'master/product_category/restore/{source}', 'Masters\ProductCategoryController@restore')->name('product_category.restore');
    Route::delete('master/product_category/delete/{source}', 'Masters\ProductCategoryController@delete')->name('product_category.delete');
    Route::resource('master/product_category', 'Masters\ProductCategoryController');
    // Product Subategory
    Route::match(['get', 'post'], 'master/product_subcategory/search', 'Masters\ProductSubcategoryController@search')->name('product_subcategory.search');
    Route::match(['put', 'patch'], 'master/product_subcategory/restore/{source}', 'Masters\ProductSubcategoryController@restore')->name('product_subcategory.restore');
    Route::delete('master/product_subcategory/delete/{source}', 'Masters\ProductSubcategoryController@delete')->name('product_subcategory.delete');
    Route::resource('master/product_subcategory', 'Masters\ProductSubcategoryController');
    // Product Color
    Route::match(['get', 'post'], 'master/color/search', 'Masters\ColorController@search')->name('color.search');
    Route::match(['put', 'patch'], 'master/color/restore/{source}', 'Masters\ColorController@restore')->name('color.restore');
    Route::delete('master/color/delete/{source}', 'Masters\ColorController@delete')->name('color.delete');
    Route::resource('master/color', 'Masters\ColorController');
    // Product Size
    Route::match(['get', 'post'], 'master/size/search', 'Masters\SizeController@search')->name('size.search');
    Route::match(['put', 'patch'], 'master/size/restore/{source}', 'Masters\SizeController@restore')->name('size.restore');
    Route::delete('master/size/delete/{source}', 'Masters\SizeController@delete')->name('size.delete');
    Route::resource('master/size', 'Masters\SizeController');
    // Product Tags
    Route::match(['get', 'post'], 'master/tags/search', 'Masters\TagsController@search')->name('tags.search');
    Route::match(['put', 'patch'], 'master/tags/restore/{source}', 'Masters\TagsController@restore')->name('tags.restore');
    Route::delete('master/tags/delete/{source}', 'Masters\TagsController@delete')->name('tags.delete');
    Route::resource('master/tags', 'Masters\TagsController');
    // Experience
    Route::match(['get', 'post'], 'master/experience/search', 'Masters\ExperienceController@search')->name('experience.search');
    Route::match(['put', 'patch'], 'master/experience/restore/{source}', 'Masters\ExperienceController@restore')->name('experience.restore');
    Route::delete('master/experience/delete/{source}', 'Masters\ExperienceController@delete')->name('experience.delete');
    Route::resource('master/experience', 'Masters\ExperienceController');
    // Blog Category
    Route::match(['get', 'post'], 'master/blog_category/search', 'Masters\BlogCategoryController@search')->name('blog_category.search');
    Route::match(['put', 'patch'], 'master/blog_category/restore/{source}', 'Masters\BlogCategoryController@restore')->name('blog_category.restore');
    Route::delete('master/blog_category/delete/{source}', 'Masters\BlogCategoryController@delete')->name('blog_category.delete');
    Route::resource('master/blog_category', 'Masters\BlogCategoryController');
    // Home Page Images
    Route::match(['get', 'post'], 'master/homepageimage/search', 'Masters\HomePageImageController@search')->name('homepageimage.search');
    Route::match(['put', 'patch'], 'master/homepageimage/restore/{source}', 'Masters\HomePageImageController@restore')->name('homepageimage.restore');
    Route::delete('master/homepageimage/delete/{source}', 'Masters\HomePageImageController@delete')->name('homepageimage.delete');
    Route::resource('master/homepageimage', 'Masters\HomePageImageController');
    // Banner Images
    Route::match(['get', 'post'], 'master/bannerimages/search', 'Masters\BannerImagesController@search')->name('bannerimages.search');
    Route::match(['put', 'patch'], 'master/bannerimages/restore/{source}', 'Masters\BannerImagesController@restore')->name('bannerimages.restore');
    Route::match(['post'], 'master/bannerimages/product_subcategory', 'Masters\BannerImagesController@product_subcategory')->name('bannerimages.product_subcategory');
    Route::delete('master/bannerimages/delete/{source}', 'Masters\BannerImagesController@delete')->name('bannerimages.delete');
    Route::resource('master/bannerimages', 'Masters\BannerImagesController');
    // Single Banner Image
    Route::match(['get', 'post'], 'master/singlebannerimage/search', 'Masters\SingleBannerImageController@search')->name('singlebannerimage.search');
    Route::match(['put', 'patch'], 'master/singlebannerimage/restore/{source}', 'Masters\SingleBannerImageController@restore')->name('singlebannerimage.restore');
    Route::match(['post'], 'master/singlebannerimage/product_subcategory', 'Masters\SingleBannerImageController@product_subcategory')->name('singlebannerimage.product_subcategory');
    Route::delete('master/singlebannerimage/delete/{source}', 'Masters\SingleBannerImageController@delete')->name('singlebannerimage.delete');
    Route::resource('master/singlebannerimage', 'Masters\SingleBannerImageController');
    // Banner Slider
    Route::match(['get', 'post'], 'master/bannerslider/search', 'Masters\BannersliderController@search')->name('bannerslider.search');
    Route::match(['put', 'patch'], 'master/bannerslider/restore/{source}', 'Masters\BannersliderController@restore')->name('bannerslider.restore');
    Route::delete('master/bannerslider/delete/{source}', 'Masters\BannersliderController@delete')->name('bannerslider.delete');
    Route::resource('master/bannerslider', 'Masters\BannersliderController');
    // Testimonial
    Route::match(['get', 'post'], 'testimonial/search', 'Testimonial\TestimonialController@search')->name('testimonial.search');
    Route::match(['put', 'patch'], 'testimonial/restore/{source}', 'Testimonial\TestimonialController@restore')->name('testimonial.restore');

app/Http/Controllers/Masters/BlogCategoryController.php
<?php

namespace App\Http\Controllers\Masters;
use Auth;
use Validator;
use DB;
use App\Masters\BlogCategory;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class BlogCategoryController extends Controller
{
    protected $sortable = [
        'id' => '_id',
        'name' => 'name'
    ];

    protected $validation_rules = [
        'name' => 'required|max:255|unique:blog_categories',
    ];

    protected $pageTitle = 'Blog Category';
    protected $activeNav = [
        'nav' => 'master',
        'sub' => 'blog_category'
    ];
    protected $breadcrumb_master = 'Blog Category';
    protected $view_master = 'master.blog_category.';
    protected $route_master = 'blog_category.';

    public function __construct()
    {
         
     $this->bladeVar['page']['title'] = $this->pageTitle;
     $this->bladeVar['page']['activeNav'] = $this->activeNav;
     $this->bladeVar['page']['breadcrumb'] = ['Home' => '/'];
     $this->bladeVar['page']['breadcrumb'][$this->breadcrumb_master] = route($this->route_master.'index');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $this->bladeVar['page']['breadcrumb'][$this->breadcrumb_master] = '';
        $this->bladeVar['results'] = BlogCategory::withTrashed()
            ->orderBy($this->sortable[$request->input('sort', 'id')], $request->input('dir', 'ASC'))
            ->paginate($this->paginate_total);
        $this->bladeVar['total_count'] = BlogCategory::withTrashed()->count();
        return view($this->view_master.'index', ['bladeVar' => $this->bladeVar]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function search(Request $request)
    {
        if (!$request->q) {
            return redirect(route($this->route_master.'index'));
        }
        $this->bladeVar['page']['breadcrumb'][$this->breadcrumb_master] = route($this->route_master.'index');
        $this->bladeVar['page']['breadcrumb']['Search'] = '';
        $this->bladeVar['results'] = BlogCategory::withTrashed()
            ->where('name', 'like', '%'.$request->q.'%')
            ->orderBy($this->sortable[$request->input('sort', 'id')], $request->input('dir', 'ASC'))
            ->paginate($this->paginate_total);
        $this->bladeVar['total_count'] = BlogCategory::withTrashed()
            ->where('name', 'like', '%'.$request->q.'%')
            ->count();
        return view($this->view_master.'index', ['bladeVar' => $this->bladeVar]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        if ($request->ajax()) {
            return view($this->view_master.'create', ['bladeVar' => $this->bladeVar]);
        } else {
            return redirect(route($this->route_master.'index'));
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = $request->all();
        $validator = Validator::make($request->all(), [
            'name' => 'required|max:255|unique:blog_categories',
        ]);
        if ($validator->passes()) {
            $product_category = BlogCategory::create([
                'name' => $request->name,
                'slug' => $this->removeSpecialChapr($request->name),
                'created_by'=>Auth::id(),
            ]);
            return response()->json([
                'success' => '<strong>Success!</strong> data saved for blog category <strong>'.$request->name.'</strong> <a href="'.route($this->route_master.'show', $product_category->_id).'" class="btn btn-sm btn-info" title="View this blog category" data-toggle="modal" data-target="#viewModal">Click here to view it</a>'
            ]);
        } 
        return response()->json(['error'=>$validator->errors()->getMessages()]); 
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, $id)
    {
        if ($request->ajax()) {
            $this->bladeVar['result'] = BlogCategory::withTrashed()->find($id);
            return view($this->view_master.'show', ['bladeVar' => $this->bladeVar]);
        } else {
            return redirect(route($this->route_master.'index'));
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, $id)
    {
        if ($request->ajax()) {
            $this->bladeVar['result'] = BlogCategory::find($id);
            return view($this->view_master.'edit', ['bladeVar' => $this->bladeVar]);
        } else {
            return redirect(route($this->route_master.'index'));
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $input = $request->all();
        $validator = Validator::make($request->all(), [
            'name' => 'required|max:255',
        ]);
        if ($validator->passes()) {
            $product_category = BlogCategory::find($id);
            $product_category->update([
                'name' => $request->name,
                'slug' => $this->removeSpecialChapr($request->name),
                'updated_by'=>Auth::id(),
            ]);
            
            return response()->json([
                'success' => '<strong>Success!</strong> Data updated for blog category <strong>'.$request->name.'</strong> <a href="'.route($this->route_master.'show', $product_category->_id).'" class="btn btn-sm btn-info" title="View this blog category" data-toggle="modal" data-target="#viewModal">Click here to view it</a>'
            ]);
        } 
        return response()->json(['error'=>$validator->errors()->getMessages()]);     
    }

     /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        BlogCategory::find($id)->delete();
        return response()->json([
            'success' => '<strong>Success!</strong> Blog Category has been deleted temporarily!'
        ]);
    }

    /**
     * Mark as deleted the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function delete($id)
    {
        BlogCategory::withTrashed()->find($id)->forceDelete();
        return response()->json([
            'success' => '<strong>Success!</strong> Blog Category has been deleted permanently!'
        ]);
    }

    /**
     * Restores deleted marked resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function restore($id)
    {
        BlogCategory::withTrashed()->find($id)->restore();
        return response()->json([
            'success' => '<strong>Success!</strong> Blog Category has been restored!'
        ]);
    }

    public function removeSpecialChapr($value){
		$title = str_replace( array( '\'', '"', ',' , ';', '<', '>','!', '@', '#' , '$', '%', '^', '&', '*' , '(', ')', '_', '-', '=' , '+', ':', '?', '.', '`', '~', '[', ']', '{', '}', '|' , '/' , '\\' , '‘' , '’' , '“', '”' , '…', '‰' ), '', $value);
		$post_title1 = str_replace( array("  "), array(" "), $title);	
		$post_title = str_replace( array(" ","'"), array("-",""), $post_title1);
		$postTitle = strtolower($post_title);
		return $postTitle;
	}	
}

resources/views/master/bannerimages/create.blade.php
<div class="row">
	<div class="col-12">
		<form action="{{ route('bannerimages.store') }}" enctype="multipart/form-data" method="POST" id="brand_form">
			<div class="form-group">
				<label class="form-control-label" for="name"><strong>Title</strong><small class="text-danger"> (required)</small></label>
				<input type="text" class="form-control" name="name" value="{{ old('name') }}" autofocus>
				<small class="form-control-feedback"></small>
			</div>
			<div class="form-group">
				<label class="form-control-label" for="product_category"><strong>Category</strong><small class="text-danger"> (required)</small></label>
				<select name="product_category" class="form-control">
					<option value=""{{ empty(old('product_category')) ? ' selected="selected"' : '' }}></option>
					@foreach ($bladeVar['product_categories'] as $key => $product_category)
					<option value="{{ $product_category->_id }}"{{ $product_category->_id == old('product_category') ? ' selected="selected"' : '' }}>{{ $product_category->name }}</option>
					@endforeach
				<option value="-1"{{ old('product_category')== -1 ? ' selected="selected"' : '' }}>Other</option>
				</select>
				<div class="other_option_wrap"></div>
				<small class="form-control-feedback"></small>
			</div>
			<div class="form-group">
				<label class="form-control-label" for="product_subcategory"><strong>Sub Category</strong></label>
				<select name="product_subcategory" class="form-control">
					<option value=""{{ empty(old('product_subcategory')) ? ' selected="selected"' : '' }}></option>
					@foreach ($bladeVar['product_subcategories'] as $key => $product_subcategory)
						<option value="{{ $product_subcategory->_id }}"{{ $product_subcategory->_id == old('product_subcategory') ? ' selected="selected"' : '' }}>{{ $product_subcategory->name }}</option>
					@endforeach
				<option value="-1"{{ old('product_subcategory')== -1 ? ' selected="selected"' : '' }}>Other</option>
				</select>
				<div class="other_option_wrap2"></div>
				<small class="form-control-feedback"></small>
			</div>
			<div class="form-group">
				<label class="form-control-label" for="btntext"><strong>Button Text</strong></label>
				<input type="text" class="form-control" name="btntext" value="{{ old('btntext') }}" autofocus>
				<small class="form-control-feedback"></small>
			</div>
            <div class="form-group">
				<label class="form-control-label" for="shortDescription"><strong>Short Description</strong></label>
				<textarea class="form-control" name="shortDescription">{{ old('shortDescription') }}</textarea>
				<small class="form-control-feedback"></small>
			</div>
			<div class="form-group">
				<label class="form-control-label" for="bannerPosition"><strong>Banner Position</strong></label>
				<select name="bannerPosition" class="form-control">
					<option value="text-center">Default</option>
					<option value="text-left">Left</option>
					<option value="text-right">Right</option>
				</select>
				<small class="form-control-feedback"></small>
			</div>
			<div class="form-group">
				<label class="form-control-label" for="image"><strong>Banner Image</strong>
				 <small class="text-danger">(required)</small></label>
				<input type="file" name="image" class="form-control">
				<small class="form-control-feedback"></small>
			</div>
			<div class="form-group text-right">
     			<button class="btn btn-success upload-image" type="submit">Submit</button>
     			<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    		</div> 
		</form>
	</div>
</div>

resources/views/master/bannerimages/edit.blade.php
<div class="row">
	<div class="col-12">
		<form action="{{ route('bannerimages.update', $bladeVar['result']->id) }}" enctype="multipart/form-data" method="POST" id="brand_form">
			{{ method_field('PUT') }}
			<div class="form-group">
				<label class="form-control-label" for="name"><strong>Title</strong><small class="text-danger">(required)</small></label>
				<input type="text" class="form-control" name="name" value="{{ old('name', $bladeVar['result']->name) }}"autofocus>
				<small class="form-control-feedback"></small>
			</div>
			<div class="form-group">
				<label class="form-control-label" for="product_category"><strong>Category</strong><small class="text-danger"> (required)</small></label>
				<select name="product_category" class="form-control">
					<option value=""{{ empty(old('product_category')) ? ' selected="selected"' : '' }}></option>
					@foreach ($bladeVar['product_categories'] as $key => $product_category)
					<option value="{{ $product_category->_id }}"{{ $product_category->_id == old('product_category',$bladeVar['result']->category) ? ' selected="selected"' : '' }}>{{ $product_category->name }}</option>
					@endforeach
				<option value="-1"{{ old('product_category')== -1 ? ' selected="selected"' : '' }}>Other</option>
				</select>
				<div class="other_option_wrap"></div>
				<small class="form-control-feedback"></small>
			</div>
			<div class="form-group">
				<label class="form-control-label" for="product_subcategory"><strong>Sub Category</strong></label>
				<select name="product_subcategory" class="form-control">
					<option value=""{{ empty(old('product_subcategory')) ? ' selected="selected"' : '' }}></option>
					@foreach ($bladeVar['product_subcategories'] as $key => $product_subcategory)
						<option value="{{ $product_subcategory->_id }}"{{ $product_subcategory->_id == old('product_subcategory',$bladeVar['result']->subcategory) ? ' selected="selected"' : '' }}>{{ $product_subcategory->name }}</option>
					@endforeach
				<option value="-1"{{ old('product_subcategory')== -1 ? ' selected="selected"' : '' }}>Other</option>
				</select>
				<div class="other_option_wrap2"></div>
				<small class="form-control-feedback"></small>
			</div>
			<div class="form-group">
				<label class="form-control-label" for="btntext"><strong>Button Text</strong></label>
				<input type="text" class="form-control" name="btntext" value="{{ old('btntext', $bladeVar['result']->btntext) }}" autofocus>
				<small class="form-control-feedback"></small>
			</div>
			<div class="form-group">
				<label class="form-control-label" for="shortDescription"><strong>Short Description</strong></label>
				<textarea class="form-control" name="shortDescription">{{ old('shortDescription', $bladeVar['result']->shortDescription) }}</textarea>
				<small class="form-control-feedback"></small>
			</div>
			<div class="form-group">
				<label class="form-control-label" for="bannerPosition"><strong>Banner Position</strong></label>
				<select name="bannerPosition" class="form-control">
				    @if($bladeVar['result']->bannerPosition == 'text-center')         
						<option value="text-center" selected="selected">Default</option>          
					@else
					    <option value="text-center">Default</option>         
					@endif
					@if($bladeVar['result']->bannerPosition == 'text-left')         
						<option value="text-left" selected="selected">Left</option>          
					@else
					    <option value="text-left">Left</option>         
					@endif
					@if($bladeVar['result']->bannerPosition == 'text-right')         
						<option value="text-right" selected="selected">Right</option>          
					@else
					    <option value="text-right">Right</option>          
					@endif	
				</select>
				<small class="form-control-feedback"></small>
			</div>
			<div class="form-group">
				<label class="form-control-label" for="image"><strong>Banner Image</strong>
				 <small class="text-danger">(required)</small></label>
				<input type="file" name="image" class="form-control">
				<small class="form-control-feedback"></small>
			</div>
			 <div class="form-group text-right">
     			<button class="btn btn-success upload-image" type="submit">Submit</button>
     			<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    		</div> 
		</form>
	</div>
</div>

resources/views/master/bannerimages/show.blade.php
<div class="row">
	<div class="col-12">
		<table class="table table-bordered table-sm mb-0">
		    <tbody>
		    	<tr>
		    		<th class="bg-faded" style="width: 8rem;">Id</th>
		    		<td>{{ $bladeVar['result']->id }}</td>
		    	</tr>
				<tr>
		    		<th class="bg-faded">Name</th>
		    		<td>{{ $bladeVar['result']->name }}</td>
		    	</tr>
		    	<tr>
		    		<th class="bg-faded">Category</th>
		    		<td>{{ $bladeVar['result']->product_category->name }}</td>
		    	</tr>
		    	<tr>
		    		<th class="bg-faded">Subcategory</th>
		    		<td>{{ $bladeVar['result']->product_subcategory->name }}</td>
		    	</tr>
				<tr>
		    		<th class="bg-faded">Button Text</th>
		    		<td>{{ $bladeVar['result']->btntext }}</td>
		    	</tr>
				<tr>
		    		<th class="bg-faded">Short Description</th>
		    		<td>{{ $bladeVar['result']->shortDescription }}</td>
				</tr>
				<tr>
		    		<th class="bg-faded">Banner Position</th>
		    		<td>
					@if($bladeVar['result']->bannerPosition == 'text-center')         
						Default                    
					@endif
					@if($bladeVar['result']->bannerPosition == 'text-left')         
						Left                
					@endif
					@if($bladeVar['result']->bannerPosition == 'text-right')         
						Right                
					@endif
					</td>
		    	</tr>
		    	<tr>
		    		<th class="bg-faded">Image</th>
		    		<td><img src="{{ asset('images/cms').'/'.$bladeVar['result']->image }}" class="thumbnail" width="150" /></td>
		    	</tr>
		    </tbody>
    	</table>
    	<span class="modalUrls hidden-xs-up" 
	    	data-edit="{{ $bladeVar['result']->deleted_at == null ? route('bannerimages.edit', $bladeVar['result']->id) : '' }}" 
	    	data-destroy="{{ $bladeVar['result']->deleted_at == null ? route('bannerimages.destroy', $bladeVar['result']->id) : '' }}" 
	    	data-restore="{{ $bladeVar['result']->deleted_at != null ? route('bannerimages.restore', $bladeVar['result']->id) : '' }}"
	    	data-delete="{{ route('bannerimages.delete', $bladeVar['result']->id) }}">
	    </span>
	</div>
</div>	    